# Generated by Django 3.1.6 on 2021-02-08 21:58

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email_address')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='last_name')),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'blog_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
