# Generated by Django 3.1.6 on 2021-02-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlogs', '0002_auto_20210208_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
