# Generated by Django 3.1.6 on 2021-02-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlogs', '0003_auto_20210208_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(db_column='blog_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
