# Generated by Django 3.1.6 on 2021-02-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlogs', '0005_auto_20210209_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
