# Generated by Django 3.1.6 on 2021-02-09 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlogs', '0006_auto_20210209_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.date(2021, 2, 9)),
            preserve_default=False,
        ),
    ]
