# Generated by Django 3.1.6 on 2021-02-09 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlogs', '0007_blog_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='mainBlogs.user'),
            preserve_default=False,
        )
    ]
