# Generated by Django 3.1.6 on 2021-02-09 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlogs', '0008_auto_20210209_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(db_column='category_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='mainBlogs.category'),
            preserve_default=False,
        ),
    ]
