# Generated by Django 3.1.6 on 2021-02-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlogs', '0009_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateField(),
        ),
    ]
