# Generated by Django 3.1.6 on 2021-02-09 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlogs', '0010_auto_20210209_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.OneToOneField(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, to='mainBlogs.category'),
        ),
    ]
