# Generated by Django 3.1.6 on 2021-02-10 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlogs', '0011_auto_20210209_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='writer',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
