# Generated by Django 3.1.6 on 2021-02-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlogs', '0012_auto_20210210_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, to='mainBlogs.category'),
        ),
    ]
